### ISSUE TITLE
Can't see full list of components in `Components` tab after 4.0.0

### ISSUE THREAD

**Issue by EWhite613** [emberjs/ember-inspector#1200]
**Describe the bug**

**To Reproduce**
1. Go to 'Components'
2. Click on 'Do a small search'
3. Notice `Components list` is some broken state and can't see any components past a certain point where it broke
4. See cannot read `.key` of null traces down to https://github.com/glimmerjs/glimmer-vm/blob/858de79dbc4d5858365ccfcfce33e57407da81d1/packages/%40glimmer/reference/lib/iterable.ts#L294

**Expected behavior**
Should see the full list

**Screenshots**
This line will repeatedly error out https://github.com/glimmerjs/glimmer-vm/blob/858de79dbc4d5858365ccfcfce33e57407da81d1/packages/%40glimmer/reference/lib/iterable.ts#L294 . If I find a small enough list I won't see this error
**Environment**
Chrome  81.0.4044.138
Ember 3.16.5
**Additional context**
Wish I could debug more, putting conditional breakpoints on the source never gets resolved even though it's evident from the error it should

**Comment by mattmarcum** [comment]
👍 I think I'm seeing this bug too, but just on the components tab in general.  Trying on ember-observer.com and the list renders correctly the first time but scrolling in the list causes rendering issues where most of the components don't show up.
![Screen Shot 2020-05-12 at 2 15 25 PM](https://user-images.githubusercontent.com/4745044/81735809-3cba5280-945b-11ea-8e53-838347fa1200.png)
![Screen Shot 2020-05-12 at 2 15 18 PM](https://user-images.githubusercontent.com/4745044/81735816-3e841600-945b-11ea-8002-28c7785647b2.png)

**Comment by rwwagner90** [comment]
@chancancode did I imagine it or did I see something about this being a bug with the keys and vertical collection in Ember 3.17 and updating to 3.18 fixed it?

**Comment by chancancode** [comment]
Yes we fixed it on master but haven’t released yet. I can do it after landing @SYU15’s other PR. In the mean time, try the nightly channel since the release will take a few days to get approved: https://chrome.google.com/webstore/detail/ibdbkmdgflhglikhjdbogjjflkialpfi

**Comment by chancancode** [comment]
Duplicate of #1195
Fixed by #1196

Pending release in stable channel

**Comment by mtrunt** [comment]
@chancancode I'm currently using the nightly extension (v4.1.0) and I'm still seeing the bug.

Only the components in the initial viewport and a few on the edges (outside viewport) seem to show properly the first time the `Components` tab is selected; however once you start scrolling no new components appear and when you scroll back up some of the previous shown components disappear.

**Comment by chancancode** [comment]
I noticed this after I posted the comment, but unfortunately even the nightly channel is currently quite behind due to long review queues (probably COVID-19 related). The current approves version of nightly is from May 1.

You can instead go [here](https://github.com/emberjs/ember-inspector/runs/672794857?check_suite_focus=true) and download the build manually. Find the artifacts drop down and click chrome.zip. Unzip it into a folder. Go to chrome://extensions, disable the ember inspector you have now and click “Load unpacked...” and select the folder you unzipped.

**Comment by chancancode** [comment]
@mtrunt @mattmarcum @EWhite613 4.1.0 has been published on the chrome store, which should fix the issue. If it doesn't, feel free to comment here and I can reopen the issue.
