### ISSUE TITLE
Cannot read property 'template' of null

### ISSUE THREAD

**Issue by jerel** [emberjs/ember-inspector#416]
I'm running Inspector 1.8.2 and after upgrading to Ember 1.3.2 I'm seeing the following error in the console:
``` js
Uncaught TypeError: Cannot read property 'template' of null
Ember.Object.extend._nodeTemplateName @ VM16952:4122
Ember.Object.extend._shouldShowNode @ VM16952:3978
(anonymous function) @ VM16952:3949
Ember.Object.extend._appendNodeChildren @ VM16952:3948
(anonymous function) @ VM16952:3954
```

I can't track down exactly what is causing it but if I disable Ember Inspector the error goes away. Sorry I don't have more info at the present and if there's something else I can do to help track this down let me know.

**Comment by pangratz** [comment]
The error happens [here](https://github.com/emberjs/ember-inspector/blob/0efcccee0b5af83033534d6b0938db938fa530ec/ember_debug/view-debug.js#L797), since  `renderNode.lastResult` is null (`renderNode.rendered` is `false`, that's why `lastResult` is `null` I guess).

**Comment by teddyzeenny** [comment]
Should be fixed by https://github.com/emberjs/ember-inspector/pull/417

**Comment by btecu** [comment]
This doesn't seem to be fixed.
I'm getting `renderNode.lastResult is null` in Firefox and `Cannot read property 'scope' of null` in Chrome when I open the extension.

**Comment by jcope2013** [comment]
still seeing issue on Chrome, ember inspector 1.8.3, ember 1.13.4

```
TypeError: Cannot read property 'template' of null
    at Ember.Object.extend._nodeTemplateName (<anonymous>:4122:43)
    at Ember.Object.extend._shouldShowNode (<anonymous>:3978:17)
    at <anonymous>:3949:18
    at Array.forEach (native)
    at Ember.Object.extend._appendNodeChildren (<anonymous>:3948:18)
    at <anonymous>:3954:16
    at Array.forEach (native)
    at Ember.Object.extend._appendNodeChildren (<anonymous>:3948:18)
    at Ember.Object.extend.viewTree (<anonymous>:3597:14)
    at <anonymous>:3553:25
```
