### ISSUE TITLE
window.postMessage(message, transferables, targetOrigin) is deprecated

### ISSUE THREAD

**Issue by blimmer** [emberjs/ember-inspector#561]
Seeing this in Chrome Canary:
```
'window.postMessage(message, transferables, targetOrigin)' is deprecated and will be removed in M54, around October 2016. Please use 'window.postMessage(message, targetOrigin, transferables)' instead. See https://www.chromestatus.com/features/5719033043222528 for more details.
```

**Comment by rwjblue** [comment]
Was fixed by https://github.com/emberjs/ember-inspector/pull/555, but needs a release.

**Comment by NickChristensen** [comment]
This seems to be breaking as of Chrome 55 (currently canary). The Ember Inspector shows "Ember application not detected", and the console shows:
```
Failed to execute 'postMessage' on 'Window': The 3rd argument is neither an array, nor does it have indexed properties.
```

**Comment by sandstrom** [comment]
FWIW I'm seeing this in 2.0.2 which was released a few days ago.

![image](https://cloud.githubusercontent.com/assets/122287/18484015/fb4fa512-79e6-11e6-93e8-52e7a7c42a9c.png)

*(click to enlarge image)*

**Comment by teddyzeenny** [comment]
That's because you keep using Ember Inspector 1.10 for Ember < 2.7 even if you have the latest extension version. We'll need to update the old snapshot...

**Comment by sandstrom** [comment]
@teddyzeenny Ah, makes sense, thanks for clarifying!

*This is only canary still, won't be in Chrome for another month or so.*

***

Unrelated: I noticed there are quite a few old issues that in my opinion could be closed.

Right now the large amount of issues makes it seem like Ember Inspector is in a bad state, but actually I find that it works really well.

Some examples of issues that (I think) can be closed:

- https://github.com/emberjs/ember-inspector/issues/130
- https://github.com/emberjs/ember-inspector/issues/119
- https://github.com/emberjs/ember-inspector/issues/115
- https://github.com/emberjs/ember-inspector/issues/141
- https://github.com/emberjs/ember-inspector/issues/142
- https://github.com/emberjs/ember-inspector/issues/143
- https://github.com/emberjs/ember-inspector/issues/43
- https://github.com/emberjs/ember-inspector/issues/170
- https://github.com/emberjs/ember-inspector/issues/248
- https://github.com/emberjs/ember-inspector/issues/259
- https://github.com/emberjs/ember-inspector/issues/268
- https://github.com/emberjs/ember-inspector/issues/429
- https://github.com/emberjs/ember-inspector/issues/448

**Comment by teddyzeenny** [comment]
@sandstrom thanks for looking into that. Yes we can probably close a lot of these issues. Though some are suggestions for possible features/improvements that haven't been developed yet, not sure how we want to handle those. We're probably going to over these tickets soon. cc @locks

**Comment by felixbuenemann** [comment]
This seems to be the reason for the following error I'm getting in 2.0.2 with an Ember 2.6.2 app using Chrome Canary 55:

```
TypeError: Failed to execute 'postMessage' on 'Window': The 3rd argument is neither an array, nor does it have indexed properties.
```

After upgrading to Ember 2.8.1 the ember-inspector starts working again.

**Comment by danielchappell** [comment]
I am seeing  the same thing as @felixbuenemann on Chrome 55 dev channel. I am on an an ember 1.10 app. I am not going to be able to upgrade ember for a while.

**Comment by nerdybeast** [comment]
I'm currently on Chrome Beta v54, ember v2.8.1, ember inspector v2.0.2, and I'm seeing the same error as @felixbuenemann

**Comment by teddyzeenny** [comment]
This should be fixed even on old Ember versions. Can someone please confirm?

**Comment by blimmer** [comment]
I still see this message every time I use the ember inspector

**Comment by teddyzeenny** [comment]
@blimmer what is your current inspector version?

**Comment by blimmer** [comment]
I guess I'm on 1.10?

![](https://i.imgur.com/5cavZnd.png)

But it looks like the current version is 2.0.3?

![](https://i.imgur.com/V6WLkfk.png)

It's not clear how to update this in chrome, though... very strange.

**Comment by teddyzeenny** [comment]
@blimmer you will always see the 1.10 version in the "Info" tab because you are on Ember < 2.7. The version I need is the one that shows up in `chrome://extensions`.

**Comment by blimmer** [comment]
![](https://i.imgur.com/QXpDE3A.png)

**Comment by teddyzeenny** [comment]
Yes you're one patch version behind.  I need confirmation that 2.0.3 solves this issue.

**Comment by blimmer** [comment]
Sorry for all the confusion - I thought Chrome would "just work" and always keep me up to date. I figured out how to force update and can confirm that the message is now gone.

**Comment by NickChristensen** [comment]
Just force-updated to Ember Inspector to 2.0.3, can confirm it works with my Ember 2.5.1 app. Thanks for this fix!

**Comment by locks** [comment]
Thanks for the confirmation everyone, and thanks for the fix @teddyzeenny!
