### ISSUE TITLE
Route Display Errors

### ISSUE THREAD

**Issue by donaldwasserman** [emberjs/ember-inspector#861]
My `Routes` tab is totally empty, and producing the following error in my console: 

```
VM3197:92 Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: routeHandler.get is not a function
Stack trace: TypeError: routeHandler.get is not a function
    at Class.buildSubTree (<anonymous>:3978:39)
    at Class.<anonymous> (<anonymous>:3893:22)
    at ComputedProperty.get (http://localhost:4200/assets/vendor.js:54505:36)
    at _get (http://localhost:4200/assets/vendor.js:53327:35)
    at Class.get (http://localhost:4200/assets/vendor.js:62854:34)
    at Class.sendTree (<anonymous>:3899:30)
    at Class.getTree (<anonymous>:3870:14)
    at sendEvent (http://localhost:4200/assets/vendor.js:52157:20)
    at Class.trigger (http://localhost:4200/assets/vendor.js:62782:33)
    at wrap (<anonymous>:3461:14)
```

Here's the data from the info tab: 

```
Ember Inspector | 3.3.2
Ember | 3.3.1
Ember Data | 3.3.1
jQuery | 3.3.1
Ember Bootstrap | 2.0.0
Ember Simple Auth | 1.7.0
```

I'm using Chrome Version 68.0.3440.106 (Official Build) (64-bit) on OSX 10.13.6 

Some extra info: Using `Ember-Engines 0.5.20` My app uses a lot of `resetNamespace: true` when nesting routes.

**Comment by rwwagner90** [comment]
Hi @donaldwasserman both engines and resetNamespace do not play nicely with Ember Inspector. There is currently no engines support, as we need to completely change the owner/container for each engine. Would you be interested in helping us come up with a nice solution for this? The first naive approach would be to have a dropdown that lets you switch between containers, but not sure where to go from there.

**Comment by donaldwasserman** [comment]
Yeah - actually, while I don't really know anything about how the inspector works, working on this beats banging my head against my desk solving some of my other app issues. 

I saw there are actually a handful other other issues on this, so I'll close this and start digging in after the holiday weekend.

**Comment by rwwagner90** [comment]
Sounds good @donaldwasserman, please reach out and I'd be glad to explain as much about inspector as I can!

**Comment by githubSathishkumar** [comment]
inspector v3.4.0 says this issue fixed. but still my routes tab empty. @rwwagner90 @donaldwasserman  no error message show in console like said in above but just empty tab. can you please let us know the bugfix status?

**Comment by rwwagner90** [comment]
@githubSathishkumar this issue was closed by @donaldwasserman, we did not implement a fix. Are you using engines and/or `resetNamespace`? I believe `resetNamespace` should work now, but there is still no engines support.

**Comment by donaldwasserman** [comment]
@githubSathishkumar It's still broken with engines as far as I know. I've stopped using engines ATM. 

@rwwagner90 I actually sort of know a path forward, but it involves refactoring how `buildSubTree()` is both called and implemented here: https://github.com/emberjs/ember-inspector/blob/master/ember_debug/route-debug.js#L123

**Comment by rwwagner90** [comment]
@donaldwasserman Are you talking about for engines or `resetNamespace`?

**Comment by donaldwasserman** [comment]
@rwwagner90 I was talking about engines. 

So the issue in `buildSubTree` is that routes from engines come back as promises, vs plain pojos from the host app's routes. So that's what's causing the routes page to totally fall over. 

The issue is that when that gets called, it's modifying the route tree by reference from the call site. So that part needs to get all taken out and the promises have to all be reduced etc etc. 

I've halfway worked through this at different points, ran out gas, and hoped someone smarter than me come up with a better approach. I'd be happy to help out on it, but haven't had the kick to actually reach out on discord 

😄

**Comment by rwwagner90** [comment]
@donaldwasserman we would love engines help 😃
